//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id_Employee { get; set; }
        public string email_employee { get; set; }
        public string username_employee { get; set; }
        public string password_employee { get; set; }
        public string akses { get; set; }
    }
}
