//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Transaksi
    {
        public int id_ProductTransaksi { get; set; }
        public string username_customer { get; set; }
        public string ProductCode { get; set; }
        public int Quantity { get; set; }
        public System.DateTime date_time { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
