//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Transaksi
    {
        public int id_Transaksi { get; set; }
        public string username_customer { get; set; }
        public string ProductCode { get; set; }
        public int Quantity { get; set; }
        public decimal SubTotal { get; set; }
        [Required]
        [Display(Name = "Tanggal Transaksi")]
        public DateTime date_time { get; set; }


        public virtual Product Product { get; set; }
    }
}
